service: myserverlessproject

provider:
    name: aws
    runtime: nodejs14.x
    profile: NaveenServerlessUser
    region: ap-south-1
    lambdaHashingVersion: 20201221

plugins:
    # - serverless-s3-sync
    - serverless-offline
    - serverless-webpack

package:
    individually: true

# custom:
#     s3Sync:
#         - bucketName: myserverlessprojectuploadbucket-123123123
#           localDir: UploadData

functions:
    getUser:
        handler: lambdas/getUser.handler
        events:
            - http:
                  path: get-user/{ID}
                  method: GET
                  cors: true

# resources:
#     Resources:
#         DemoBucketUpload:
#             Type: AWS::S3::Bucket
#             Properties:
#                 BucketName: myserverlessprojectuploadbucket-123123123
